logging:
  level:
    org.apache.catalina.core: ERROR
    org.springframework: ERROR
    com.zaxxer.hikari: warn
    mx.gob.sep: INFO
  pattern:
    console: "%highlight([%-5level]) %d{dd-MM-yyyy HH:mm:ss.SSS} [RegistroREC] [ %-25.25thread ] - [ ID:124, USUARIO:%X{user:-NO USER}, IP:%X{ip:-localhost}]  %magenta([ CLASS: %-50.50c ]) - %cyan([ METHOD: %-40.40M{39} ]) --- [ %m ] %n"

app:
  header:
    title: Registro para el Reconocimiento de Proactividad Academica

  menu:
    title:
      participacion: Datos de participación
      terminar: Finalizar proceso
      visualizacion: Visualización de datos
      datospersonales: Datos personales
      terminado: Registro finalizado
      registro: Finalización de registro


